[project]
name = "apify-google-Hotels-api"
version = "0.1.0"
description = "Google Hotels API - Access Google Hotels Using Python"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apify-client>=2.3.0",
    "python-dotenv>=1.2.1",
    "rich>=14.2.0",
]
